pyneuromodulation/settings.py
pyneuromodulation/tests/test.py

Create test for settings

---

examples/settings.json
pyneuromodulation/features.py
pyneuromodulation/sharpwaves.py
pyneuromodulation/tests/test.py

@richardkoehler  if you want to look, I adapted the sharpwave estimation. It took me quite some time to get around this by not having the same idea how I programmed it previously :) 
The settings.json have now an option to enable the separate features, but also different estimators. 
This speeds up the sharpwave estimation by a factor of 10-20, by specifically turning off the sw features it should be faster. 
The test.py is adapted, but I have to think of a separate test to see if the features are correctly estimated still. 
Fixes #9

Adapted sharpwave features

---

examples/example_ML.py
examples/feature_reader_example.py
pyneuromodulation/nm_decode.py
pyneuromodulation/nm_reader.py

add ML BayesOpt clean run

---

pyneuromodulation/IO.py
pyneuromodulation/start_BIDS.py

Pass individual settings to start_BIDS and make grid estimation optional

small fixes

---

examples/example_BIDS.py
pyneuromodulation/bandpower.py
pyneuromodulation/features.py
pyneuromodulation/filter.py
pyneuromodulation/nm_reader.py
pyneuromodulation/run_analysis.py
pyneuromodulation/settings.py
pyneuromodulation/start_BIDS.py
pyneuromodulation/tests/test.py

@timonmerk 
test.py didn't work for me because of the paths. I think the main issue is the function os.pardir, which maybe works differently depending on your current working directory? Not quite sure.. I fixed some of the paths but maybe you should check if the tests still work for you as well!

Fix test paths

---

examples/example_read_features.py
pyneuromodulation/nm_decode.py
pyneuromodulation/nm_reader.py

fix grid point analysis

---

examples/cohort_wrapper.py
pyneuromodulation/nm_analysis.py
pyneuromodulation/nm_decode.py
pyneuromodulation/nm_features.py
pyneuromodulation/nm_settings.json
pyneuromodulation/nm_stft.py

+Kalman FIlter for stft features

Add Plotting function + nm_decoder for all channels

---

pyneuromodulation/nm_settings.py

@timonmerk Please check if this also works on your system!
Closes #118

Fix path bug

---

py_neuromodulation/nm_BidsStream.py

Fix timestamp for cases when data is resampled

---

py_neuromodulation/nm_eval_timing.py
py_neuromodulation/nm_normalization.py
py_neuromodulation/nm_run_analysis.py

- Computation time of feature normalization was improved
- Memory usage of feature normalization was improved
- nm_eval_timing was repaired, as these changes broke the api
closes #136

Optimize speed of feature normalization

---

py_neuromodulation/nm_analysis.py
py_neuromodulation/nm_eval_timing.py
py_neuromodulation/nm_normalization.py
py_neuromodulation/nm_plots.py
py_neuromodulation/nm_projection.py
py_neuromodulation/nm_run_analysis.py
py_neuromodulation/nm_stream.py

Fix call to project_cortex in Projection.__init__ (and minor style fixes)

Fix plotting projection

---

py_neuromodulation/nm_eval_timing.py
py_neuromodulation/nm_notch_filter.py
py_neuromodulation/nm_run_analysis.py
py_neuromodulation/nm_stream.py

Previous timings:
time_rereference : 1.57ms
time_resample : 2.2ms
time_notchfilter : 15.91ms
time_feature_norm : 0.18ms
time_projection : 4.07ms
time_fft : 0.3ms
Now with precomputed notch filter:
time_rereference : 1.79ms
time_resample : 2.5ms
time_notchfilter : 3.7ms
time_feature_norm : 0.28ms
time_projection : 4.99ms
time_fft : 0.44ms

Speedup notchfilter

---

py_neuromodulation/nm_BidsStream.py
py_neuromodulation/nm_define_nmchannels.py
py_neuromodulation/nm_stream.py

Changes:
- No functionality was changed
- Type hints added
- Code cleaned up
- More informative error messages
Additionally:
- Maybe think about changing target keywords only to: ["mov", "squared"] ?
Listing all possible channels from our analysis like we do now is probably not very elegant and not helpful for other people that might have other channels (e.g. "squared_accelerometer" or something similar)

Refactor nm_define_nmchannels

---

environment.yml
py_neuromodulation/nm_features.py
py_neuromodulation/nm_linelength.py
py_neuromodulation/nm_mne_connectiviy.py
py_neuromodulation/nm_run_analysis.py
py_neuromodulation/nm_settings.json

Fix issue regarding feature_sampling_rate to be float below 0

Add MNE Connectiviy Features + Line Length

---

py_neuromodulation/nm_coherence.py
py_neuromodulation/nm_settings.json

add coh features

---

py_neuromodulation/nm_rereference.py
tests/test_rereference.py

- Re-referencing is now a simple matrix multiplication, which reduces computation time by about 90%
- Added unit test to make sure the new function provides the same results as the old re-referencing

Optimize re-referencing

---

py_neuromodulation/nm_IO.py
py_neuromodulation/nm_artifacts.py
py_neuromodulation/nm_stream_offline.py
pyproject.toml
tests/test_target_channel_add.py

Fix add targets

---

.gitignore
py_neuromodulation/_write_example_dataset_helper.py
py_neuromodulation/nm_bursts.py
py_neuromodulation/nm_filter.py
py_neuromodulation/nm_filter_preprocessing.py
py_neuromodulation/nm_oscillatory.py
py_neuromodulation/nm_run_analysis.py
py_neuromodulation/nm_settings.json
tests/conftest.py
tests/test_fooof.py
tests/test_nm_filter.py
tests/test_preprocessing_filter.py
tests/test_rereference.py

- Added settings file for bandpass, bandstop, lowpass and highpass filter.
- Settings.json was adapted to account for added preprocessing method.
- The nm_filter object was adjusted s.t. the added dimension is trimmed, s.t. the preprocessing modules don't change the data shape before feature computation.

Add preprocessing filter

---

docs/source/contributing.rst
docs/source/index.rst
docs/source/nm_analysis.rst
docs/source/nm_stream.rst
docs/source/sg_execution_times.rst
examples/plot_1_example_BIDS.py
py_neuromodulation/nm_bursts.py
pyproject.toml

Add contribution section

---

py_neuromodulation/nm_settings.yaml
py_neuromodulation/nm_sharpwaves.py

add number of peaks features to sharpwaves

---

gui_dev/src/pages/Channels/Channels.jsx
gui_dev/src/pages/Settings/Settings.jsx

Smallest PR ever.
I noticed there's an error that happens (even before my update) that happens right after loading the settings page. It's not crashing the page obviously but I wonder if we know about this and want to look into it.
I tested the flow after my changes at everything seemed to be working.

[FE] Gui button edits

---

gui_dev/src/stores/sessionStore.js

Fixes https://github.com/neuromodulation/py_neuromodulation/issues/395

fix issue with when opening file
