neuromodulation/py_neuromodulation

- examples/test_features.py
- pyneuromodulation/rereference.py
@timonmerk  So I was pulling all the information extraction from df_M1, like cortex_idx and subcortex_idx etc., into the rereference module, to make the actual analysis script (e.g. test_features) a bit cleaner. This got me thinking that we should maybe initialize the settings as a class, into which we load the settings.json and M1.tsv. We could then get the relevant information via functions e.g. ch_names(), used_chs(), cortex_idx(), out_path() etc. What do you think?
The pull request doesn't implement the class yet or anything, I only pulled the cortex_idx etc. into the rereference initialization.
> Update rereference and test_features

- pyneuromodulation/nm_normalization.py
@timonmerk 
Should we add zscore-median as method, where the median is substracted instead of the mean? This could potentially be better for handling movement artifacts.
> Add zscore-median as method

- py_neuromodulation/nm_IO.py
- py_neuromodulation/nm_stream.py
- sampling freq "fs" written out was the original freq, not the final freq
- SIDECAR.json now includes:
- "fs"
- "original_fs"
- "ch_names" (channel names used to calculate features)
- Small typo in "_set_notch_filter" fixed
- Type hinting for "fs" fixed (can be float or int)
> Fix fs in SIDECAR.json

- py_neuromodulation/nm_rereference.py
- A bug was present where channels were used even when used was 0
-> Now indexes are split into "*_used" and "*_good"
- Duplicates in the docstring were removed
- The separator for a multiple-channel reference is now "&" instead of "+"
- "+" may also be used for DBS channels, e.g. "LFP_2+3+4_STN_BS"
- if you want a multiple-channel reference you can now write "LFP_2+3+4_STN_BS&LFP_5+6+7_STN_BS"
> Bugfix RT_rereference

- py_neuromodulation/nm_decode.py
ClassMissingException previously printed the message "only one class present" even when the module nm_decode was simply initialized. Now ClassMissingException only prints this message when an Exception is actually raised.
Additionally, an individual message can be passed upon raising the Error, to potentially discern where exactly in the module the Error was raised.
> Fix ClassMissingException

- py_neuromodulation/nm_analysis.py
The current code only worked if you passed the filename with the suffix ".vhdr" because of the hardcoded `-len(".vhdr")`. I got an error because of only passing the files basename. My proposed fix should now work in both cases.
On a note, I think it is not necessarily recommended to use "import _pickle", because the standard module "import pickle" automatically does just this (https://stackoverflow.com/questions/19191859/what-difference-between-pickle-and-pickle-in-python-3).
Changes:
- pass responsability for retrieving file stem to Path()
- add missing comma after "SQUARED_ROTAWHEEL"
- sort imports
> Fix pathing problem in nm_analysis

- py_neuromodulation/nm_rereference.py
- py_neuromodulation/nm_stream.py
- py_neuromodulation/start_LSL.py
- Fixed bug with average reference, when channels were marked as "bad"
- Refactored RT_rereference so that reference ids for each channel willnot be re-calculated at each rereference() call, only once when initializing the class instance. This should bring some performance improvement.
- Average references for different channel types (ECOG, LFP, SEEG, LFP) are now automatically handled and not explicitly for each different channel type.
- Had to remove split_data (but I think this wasn't used anyway, right?)
> Refactor nm_rereference

- examples/example_BIDS.py
- py_neuromodulation/nm_BidsStream.py
- py_neuromodulation/nm_define_nmchannels.py
- py_neuromodulation/nm_stream.py
@timonmerk
As you suggested in the last PR #162, I added `mov_substrs` as an argument to the function:
- I renamed it to `target_keywords`, because you might be decoding something else than movement, so the name is a bit more universal
- As default arguments I added `("mov", "squared", "label")`. I added label here again, so that the default value is a bit more universal and people are not restricted to movement or classification ("squared")
- I changed the default types of used_types and target_keywords to tuples, because probably the default values should be an immutable, right?
- I saw that you changed the default in nm_BidsStream to `used_types:list = ["ecog"]`. So the default in nm_BidsStream now corresponds to `ECOG_ONLY = True`, but before it was `False`. Is that intended? I don't …
> Add `target_keywords` as argument

- examples/example_BIDS.py
- py_neuromodulation/__init__.py
- py_neuromodulation/nm_IO.py
- py_neuromodulation/nm_filter.py
- py_neuromodulation/nm_stream_abc.py
- py_neuromodulation/nm_stream_offline.py
- scripts/trd_analysis_epochs.py
- scripts/trd_analysis_stream_plotting.py
I worked on some refactoring based on the previous PR:
- move `folder_name` and `out_path_root` (former `path_out`) to `run` function
- remove `BidsStream` from `nm_stream_offline`
- add to `nm_IO` `get_coord_list` function for getting BIDS coordinates information and move call into def `read_BIDS_data`
- add `init_stream` function in `nm_stream_abc` 
The last point solves the following issues:
- the previous `set_run` method was called from the `run` method, in this way all parameters for the specific "nm_" feature and preprocessing parameters would have to be supplied to the `run` function, so the `init_stream` method decouples this; in this way e.g. `nm_resample.Resample` or `nm_filter.NotchFilter` can be supplied externally to the stream.
- the `coords` parameter can thus be specified …
> refactor offline stream

- packages/realtime_decoding/src/realtime_decoding/features.py
- packages/realtime_decoding/src/realtime_decoding/run_decoding.py
- packages/realtime_decoding/src/realtime_decoding/trainer.py
Added super simplistic training routine.
Points to check:
- It might be not so visually clear to see the print line arguments, corresponding to MOVE or REST
- Right now there is only a counter `training_samples` in features.py. So for e.g. 30s training, each class having 15s training time, we would need to calculate how many samples that correspond to, e.g. right now with 20ms: 15*(1/0.02s)
- I terminate the `Features.run` function in case training is done with a simple `break`, I think that should work, but I'm not sure
- I assume that .hdf5 saving with timeflux works. Otherwise we would need to collect the features independently, but I think this way should be fine, the `save` node just needs to be enabled
> Add training routine

- py_neuromodulation/nm_coherence.py
- py_neuromodulation/nm_mne_connectivity.py
- py_neuromodulation/nm_stream_offline.py
- pyproject.toml
Adding joblib feature parallelization.
- Added check if parallelization can be performed in `nm_stream_offline`
- Changed class attribute to instance attribute in `nm_mne_connectivity`
- Added dependency of joblib
-  Added Tests for equal sequential and parallel computation
> Parallel processing pr

- py_neuromodulation/nm_normalization.py
Simple change to check for NaN's before using Numpy's nanmean, nanmedian and nanstd functions, and use their non-nanproof versions when possible. In my test is almost twice as fast, but of course this could be worse performance wise in the case that most/all of the batches contain NaNs, but the cost of checking for NaN's is low so it's probably faster in most cases, although this should be tested with real data containing NaN's.
I also tested different ways to check for NaN's and the fastest was given by [this StackOverflow comment ](https://stackoverflow.com/questions/6736590/fast-check-for-nan-in-numpy#comment68299587_6736970)
Minor change to add a match/case block to check normalization method, although the speed improvement is not relevant here it fits better imho.
Comparison of time …
> Avoid use of Numpy nan statistics if possible

- py_neuromodulation/nm_bursts.py
Small change to simplify the code of nm_bursts.py function `get_burst_amplitude_length`, to make it faster by removing the line
```Python
if burst_state == True:
```
which was responsible for most of the slowdown, maybe due to the CPU not being able to pipeline the computations due to the next value of the `burst_state` variable being impossible to predict. Pre-calculating burst indexes with 
```Python
burst_states = np.where(deriv==True)[0]
```
fixed the issue, and made the function about 3x faster.
Benchmark code:
```Python
NUM_CHANNELS = 5
NUM_DATA = 100000
sfreq = 1000 # Hz
feature_freq = 3 # Hz
n = 3 # Repeats
np.random.seed(0)
elapsed = 0
for i in range(n):
data = np.random.random([NUM_CHANNELS, NUM_DATA])
t = time.time()
stream = nm.Stream(sfreq=sfreq, data=data, settings=settings, …
```
> Bursts feature performance improvement

- py_neuromodulation/nm_sharpwaves.py
When running the profiler on an offline analysis _sharpwaves_ was, together with _bursts_, one of the more computationally costly features to calculate. I made some changes that brought the computation time for this feature down to 50%:
Commit 1 - Simplify `_get_peaks_around`: The profiler showed a very high amount of calls to `argsort` from the method `_get_peaks_around` and I realized that for each trough in the data, this function was being called and subsequently calling argsort twice. I worked out the logic of the function and realized that since `scipy.signal.find_peaks` is returning the peak indexes in order the calculation can be reduced to an array filtering operation which is much faster. 
Commit 2 - Single pass adjacent peak finding: Even with the previous change, it seemed to …
> Sharpwaves performance fixes

- py_neuromodulation/nm_stream_offline.py
This should fix the problem in #300, by returning the transposed version of the data from _OfflineStream._handle_data when the input is given in the form of a DataFrame. I also fixed the Error message that caused the confusion in the first place.
Additionally, this raises the issue of having 2 different expected data input layouts:
- For numpy arrays: (n_channels, n_timepoints) 
- For pandas dataframes: (n_timepoints, n_channels)
This is AFAIK not very well explained in the documentation.
Changing the expected dimensions of the np.array is most likely impossible since it would break compatibility. But also changing the dimensionality of dataframes is probably also not a good idea since rows for datapoints and columns for features is the standard way people organize data.
So I have settled …
> Fix handling of dataframe input, issue #300

- .github/workflows/tests.yml
- .gitignore
- README.rst
- pyproject.toml
So, as I mentioned in issue #310 I wanted to see if Rye could speed up setting up the testing environment for Github actions automated testing.
In the end I made several changes:
- Rye was not the adequate tool, is more a development environment manager than a package installer, so I used uv (https://astral.sh/blog/uv) instead, which is created by the same developers and it's what Rye uses under the hood.
- The Github action for setting up uv (https://github.com/drivendataorg/setup-python-uv-action/) also handles dependency caching which is a cool feature, although even without the cache the whole process if very fast (it's about 7 seconds to download and install everything)
- I got rid of Tox since it wasn't doing really anything for us at the moment. Right now the only real work it was …
> Improve Github actions testing workflow

- py_neuromodulation/nm_generator.py
- py_neuromodulation/nm_run_analysis.py
- py_neuromodulation/nm_stream_offline.py
- tests/test_lsl_stream.py
Hi @timonmerk, I made some changes on top of the recent LSL merge. Summary:
- Remove settings parameter from LSLOfflinePlayer since it's not used, as the sampling frequency  is passed in another parameter
- Defer LSLStream imports
- Fix a typing error
- Remove a couple variables
- Changed a couple errors for warnings:
- If both a filename and a data array was passed to LSLOfflinePlayer, it would throw an error. I changed it to a warning and defaulted to using the file as data source.
- If _GenericStream was reading from an LSLStream with different frequency that the one that was passed it would  throw an Exception, instead I think we can warn the user and default to the LSLStream frequency.
It's in general problematic to have 2 sources of truth like in the case of GenericStream getting an …
> Minor changes on top of mne_lsl merge

- examples/plot_0_first_demo.py
- examples/plot_1_example_BIDS.py
- examples/plot_2_example_add_feature.py
- examples/plot_3_example_sharpwave_analysis.py
- examples/plot_4_example_gridPointProjection.py
- examples/plot_6_real_time_demo.py
- examples/plot_7_lsl_example.py
- py_neuromodulation/nm_analysis.py
- py_neuromodulation/nm_projection.py
- py_neuromodulation/nm_run_analysis.py
- py_neuromodulation/nm_stream_abc.py
- py_neuromodulation/nm_stream_offline.py
- tests/test_fooof.py
While I was working on bursts vectorization, I was checking the profiling results and I noticed an unusual amount of time being spent in `pd.Series.__init__` and also in `_add_timestamp`. In total, they accounted for 6 to 7% of the running time.
- `pd.Series.__init__`: 2.5%
- `_add_timestamp`: 3.8% 
I realized this was due to the transformation of the dictionary of feature results `feature_dict` to a pd.Series `feature_series`, as well as the modification of a pd.Series instead of a `dict` which comes at a much greater cost due to Pandas overhead, possibly having to move the entire series around in memory, etc. This was done, I imagine, to facilitate some of the computations that were done on that series, mainly the cortex/subcortex projection. But paying a 7% of the running time is too …
> Generate results directly from feature_dict instead of pd.Series

- py_neuromodulation/nm_hjorth_raw.py
- py_neuromodulation/nm_linelength.py
So I was looking at the profiling info, and I was quite happy that Bursts and Sharpwaves are now as fast as Hjorth. But after messing with Bursts and Sharpwaves for so many hours, I know that they're very complex features, so how come Hjorth is taking so long? Is it also super-complex?
Well it turns out no, it was just doing quite a lot of redundant work so I streamlined it a bit, which brought the computation time to 20% of the previous code, or a 5x speed-up.
Summary of changes:
- Do all the `diff`, `var` and `sqrt` calculations step-wise storing intermediate results to avoid repeating calculations
- Use the `axis` argument to run the calculations on the entire dataset at once, rather than 1 channel at a time
- Call `nan_to_num()` only once at the very end, it's more efficiente and also …
> Optimize Hjorth and LineLength calculation

- .gitignore
- py_neuromodulation/nm_mne_connectivity.py
I know you're expecting news on the GUI, but since I wanted to present also about the speed optimizations next week and I know that some people involved in the MNE package might be around the lab I did some investigation in one of the 3 features that were still weighing us down too much for real-time processing: MNE connectivity (the other 2 being Bispectra and FOOOF)
So I realized that Epochs.__init__() and RawArray.__init__() were taking so much computation time, that I wondered whether running the constructors every time was even doing anything. So I went through all the lines of code taking notes and figured, no, the 200-300 lines of constructor for each class are doing nothing for us at least with our current parameters. So I basically bypassed those by just replacing the Numpy array …
> MNE connectivity 2x speed-up

- py_neuromodulation/features/bispectra.py
Reduces some jankiness with the bispectra feature now that PyBispectra v1.2 is available (was already pinned in #355).
> Update bispectra feature

- py_neuromodulation/analysis/decode.py
For visualization purposes I included an extra channel in the feature array, which was neither a label nor a used channel. However, it was still included in the combined data array and thus, for decoding. The proposed change makes sure that only those channels that are also present in the used_ch list (and not all apart from the label and the time) are included in the combined dataset.
> Fixed use of non-target/decoding channel in the combined setting

- examples/plot_0_first_demo.py
- py_neuromodulation/gui/backend/app_backend.py
- py_neuromodulation/gui/backend/app_manager.py
- py_neuromodulation/gui/backend/app_pynm.py
- py_neuromodulation/stream/stream.py
- py_neuromodulation/utils/file_writer.py
- pyproject.toml
- start_LSL_stream.py
- change storage from database to messagepack
- fix async run function. Call run function within thread instead of process
> Refactor storage
